version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/lmsdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: lmsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "1123:5432"  # Windows наружный порт